export const LOGIN_USER_REQUESTING = 'LOGIN_USER_REQUESTING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const ME_REQUESTING = 'ME_REQUESTING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_ERROR = 'ME_ERROR';

export const REGISTER_REQUESTING = 'REGISTER_REQUESTING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_TOKEN = 'GET_TOKEN';
